title: The Lilo Zine
description: A living archive in motion.
url: "https://lilozine.github.io"   # your live URL
baseurl: ""                         # empty because it's a user site

# optional: theme line (not required to *run*)

# plugins:


# remote_theme: bitbrain/jekyll-dash # remote_theme: owner/repo-name

